# action.yml
name: "setup-tcmalloc"
description: "An action to download, install, and cache tcmalloc on Linux runners"
author: "Jason Pearson"
inputs:
  tcmalloc-version:
    description: "Version of tcmalloc to use"
    required: "true"
    default: "5.3.0"
outputs: {}

runs:
  using: "composite"
  steps:

    # - name: "Restore tcmalloc"
    #   if: runner.os == 'Linux'
    #   id: cache-tcmalloc
    #   uses: actions/cache/restore@v4
    #   with:
    #     path: ${{ runner.os == 'Linux' && '/tmp/libtcmalloc.so' }}
    #     key: v7-${{ runner.os }}-tcmalloc-${{ inputs.tcmalloc-version }}

    # - name: "Relocate tcmalloc to expected directory"
    #   if: ${{ runner.os == 'Linux' && steps.cache-tcmalloc.outputs.cache-hit == 'true' }}
    #   shell: bash
    #   run: |
    #     if [ "${{ runner.os }}" == "Linux" ]; then
    #       mkdir -p /usr/local/lib
    #       sudo cp /tmp/libtcmalloc.so /usr/local/lib/
    #     fi

    - name: "Download & install tcmalloc"
      if: ${{ runner.os == 'Linux' && steps.cache-tcmalloc.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        if [ "${{ runner.os }}" == "Linux" ]; then
          sudo apt-get install google-perftools
        fi

    - name: "Configure LD_PRELOAD (or equivalent)"
      if: runner.os == 'Linux'
      shell: bash
      run: |
        if [ "${{ runner.os }}" == "Linux" ]; then
          echo 'LD_PRELOAD=/usr/local/lib/libtcmalloc.so' >> $GITHUB_ENV
          mkdir -p /tmp
          cp /usr/local/lib/libtcmalloc.so /tmp/
        fi

    # - name: "Save tcmalloc"
    #   uses: actions/cache/save@v4
    #   if: ${{ runner.os == 'Linux' && steps.cache-tcmalloc.outputs.cache-hit != 'true' }}
    #   with:
    #     path: ${{ runner.os == 'Linux' && '/tmp/libtcmalloc.so' }}
    #     key: v7-${{ runner.os }}-tcmalloc-${{ inputs.tcmalloc-version }}

    # - name: "Remove download directory"
    #   if: ${{ runner.os == 'Linux' && steps.cache-tcmalloc.outputs.cache-hit != 'true' }}
    #   shell: bash
    #   run: |
    #     rm -rf tcmalloc-${{ inputs.tcmalloc-version }}

branding:
  icon: "cpu"
  color: "blue"

